language: php
php:
- '7.2'

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev

script:
  - composer run-script run-tests
  - composer run-script analyze-code
  - composer run-script fix-cs